baseURL = "https://jupiter263.github.io/Jovian/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
title = "Jovian"
hasCJKLanguage = true
[languages]
  [languages.zh-cn]
    languageName = "中文"
    title = "Jovian"
    weight = 1
  [languages.en]
    languageName = "English"
    title = "Jovian"
    weight = 2
  [languages.ja]
    languageName = "日本語"
    title = "Jovian"
    weight = 3
    hasCJKLanguage = true

[permalinks]
  post = "/p/:slug/"

[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true

  [params.sidebar]
    emoji = "🪐"
    subtitle = "Jupiter's notes"
    compact = false

  [params.article]
    toc = true

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"