baseURL = "https://jupiter263.github.io/Jovian/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
title = "Jovian"
hasCJKLanguage = true

[permalinks]
  post = "/p/:slug/"

[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true

  [params.sidebar]
    emoji = "🪐"
    subtitle = "Jupiter's notes"

  [params.article]
    toc = true

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"